# Chapter 2: Foundations of Data Manipulation

## 1. Introduction

Now that we understand how to use Python lists, let's level up our data handling skills. In a clinical setting like City Medical Center, we often work with large, structured datasets—like hourly vitals for an entire ICU wing. While lists are flexible, they aren't optimized for the fast, complex mathematical operations we need. This is where NumPy comes in. Think of NumPy arrays as a supercharged version of lists, designed for high-performance numerical computing.

In this section, you will learn how to create and inspect these foundational data structures. By the end, you will be able to transform raw data from Python lists into structured NumPy arrays, the first critical step in any robust data analysis pipeline.

---

## 2. Key Concepts and Definitions

- **Array**: A data structure that stores a collection of items of the same data type (homogeneous). This uniformity is what allows NumPy to perform mathematical operations on the entire collection at once, a process called vectorization, which is significantly faster than looping through a Python list. In medicine, an array could efficiently store thousands of continuous glucose monitoring readings.

- **`.shape`**: A tuple representing the array's dimensions. For a 2D array, it's `(rows, columns)`, like a spreadsheet. For an array of patient vitals, a shape of `(3, 3)` means 3 patients (rows) and 3 vital signs (columns).

- **`.ndim`**: The number of dimensions or axes. A 1D array (like a single patient's heart rate over time) has `1` dimension, while a 2D array or matrix (like vitals for multiple patients) has `2`.

- **`.size`**: The total number of elements in the array. It's the product of the dimensions in `.shape` (e.g., for a `(3, 3)` array, the size is 3 * 3 = 9).

- **`.dtype`**: The data type of the elements (e.g., `int64`, `float64`). Knowing the `dtype` is crucial for memory management and preventing calculation errors.

- **Type Up-casting**: The process where NumPy automatically converts all elements to the most precise data type when an array is created from mixed-type data. For example, if a list of glucose readings contains one float (`115.5`), all integer readings are converted to floats to prevent data loss.

---

## 3. Main Content

This section covers the primary methods for creating and inspecting NumPy arrays. Each function is a fundamental tool for initializing and understanding your data structures.

> **In Practice:**
> At City Medical Center, analyzing trends across thousands of patient lab results requires rapid calculations. Using NumPy arrays instead of Python lists can reduce computation time from minutes to seconds, enabling clinicians to derive insights and make decisions more quickly.

### 3.1 Creating Arrays from Lists

The most direct way to create an array is by converting a Python list or list of lists using `np.array()`.

In [ ]:
import numpy as np

# Hourly post-meal glucose readings (mg/dL)
glucose_readings = [110, 115, 120, 118, 122]
np_glucose = np.array(glucose_readings)

print(np_glucose)

# Expected Output:
# [110 115 120 118 122]

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




For multi-dimensional data, you can use nested lists. Each inner list becomes a row in the resulting 2D array, forming a matrix perfect for organized data like patient vitals.

In [ ]:
import numpy as np

# Vitals for 3 patients: [Heart Rate (bpm), Systolic Blood Pressure (mmHg), Oxygen Saturation (%)]
patient_vitals = [
    [72, 120, 98],
    [88, 125, 96],
    [65, 110, 99]
]
np_vitals = np.array(patient_vitals)

print(np_vitals)

# Expected Output:
# [[ 72 120  98]
#  [ 88 125  96]
#  [ 65 110  99]]

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




### 3.2 Inspecting Array Attributes

After creating an array, use its attributes to verify its structure. This is a critical step for debugging and data validation.

In [ ]:
import numpy as np

# Vitals for 3 patients: [Heart Rate (bpm), Systolic Blood Pressure (mmHg), Oxygen Saturation (%)]
patient_vitals = [
    [72, 120, 98],
    [88, 125, 96],
    [65, 110, 99]
]
np_vitals = np.array(patient_vitals)

# Inspecting the 2D np_vitals array
print("Shape:", np_vitals.shape)
print("Dimensions:", np_vitals.ndim)
print("Size:", np_vitals.size)
print("Data Type:", np_vitals.dtype)

# Expected Output:
# Shape: (3, 3)
# Dimensions: 2
# Size: 9
# Data Type: int64

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




### 3.3 Creating Arrays with Functions

NumPy provides functions to generate arrays without manually typing out a list.

Use `np.arange(start, stop, step)` to create an array of sequential numbers, which is useful for generating hourly time points for an observation period.

In [ ]:
import numpy as np

# Create an array representing 24 hourly time points
time_points = np.arange(24) # Integers from 0 to 23

print(time_points)

# Expected Output:
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




Use `np.linspace(start, stop, num)` to create an array with a specific number of evenly spaced values. This is ideal for defining dosage levels in a drug trial.

In [ ]:
import numpy as np

# Create 10 evenly spaced dosage levels from 5 mg to 50 mg
dosage_levels = np.linspace(5, 50, 10)

print(dosage_levels)

# Expected Output:
# [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




> **Reflection Moment:**
> You've seen `np.arange()` for creating integer steps (like hours in a day) and `np.linspace()` for creating a specific number of points between two values (like dosage levels). When might you choose one over the other for tracking a patient's temperature over a 48-hour period? What are the advantages of each approach?

### 3.4 Creating Placeholder Arrays

It's often efficient to create placeholder arrays of a desired shape with `np.zeros()` or `np.ones()` and fill them with data later. This pre-allocates the necessary memory.

> **Pro Tip:**
> Pre-allocating an array with `np.zeros()` or `np.ones()` is a professional best practice. It reserves a contiguous block of memory upfront, which is more efficient than incrementally growing a data structure. This is especially important when logging large amounts of data from medical devices in real-time.

In [ ]:
import numpy as np

# Create a 24x3 array of zeros for hourly [HR, SBP, SpO2]
# Initializes as float64 by default, a good choice for measurements that might require decimals.
# In a real Electronic Health Record (EHR), some of these values (like Heart Rate) might be stored as integers, so choosing the right dtype is key.
vitals_log = np.zeros((24, 3))
print("Vitals Log Placeholder:")
print(vitals_log)

# Create a 2x2 array of ones to represent pre-op checklist status (1 = complete)
task_status = np.ones((2, 2), dtype=np.int8)
print("\nTask Completion Status:")
print(task_status)

# Expected Output:
# Vitals Log Placeholder:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  ...
#  [0. 0. 0.]]
#
# Task Completion Status:
# [[1 1]
#  [1 1]]

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




### 3.5 Managing Data Types

Controlling the data type of your array is key to managing memory and precision.

> **Important:**
> Choosing the correct `dtype` is a trade-off between memory and precision. Using `np.float64` ensures high precision for sensitive measurements but uses more memory. Using `np.int8` is very memory-efficient for whole numbers between -128 and 127 (like fall counts), but would be inappropriate for storing body temperature or lab results with decimals. Mismatched `dtype`s can lead to data loss or errors in clinical calculations.

In [ ]:
import numpy as np

# Drug doses in milligrams (mg)
doses_mg = [50, 100, 75]
np_doses = np.array(doses_mg, dtype=np.float64)

print(np_doses)
print(np_doses.dtype)

# Expected Output:
# [ 50. 100.  75.]
# float64

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




NumPy's automatic up-casting is helpful but can be a silent source of bugs.

> **Debug Note:**
> Automatic type up-casting is helpful but can be a silent source of bugs. If you expect an array of integers but accidentally include one float, the entire array becomes float. This can increase memory usage unexpectedly or cause issues with systems that require integer inputs. Always double-check `.dtype` after creating an array from mixed-type data.

In [ ]:
import numpy as np

# A mix of integer and float glucose readings (mg/dL)
mixed_glucose = [110, 115.5, 120]
np_mixed_glucose = np.array(mixed_glucose)

print(np_mixed_glucose)
print(np_mixed_glucose.dtype)

# Expected Output:
# [110.  115.5 120. ]
# float64

**Try it yourself:** Modify the code above or write your own version

In [ ]:
# TODO: Write your code here
# Hint: Try modifying the example above




---

## 4. Practice Exercises

### Exercise 1: Structure and Inspect Lab Results Basic

**Objective:** Create a 2D NumPy array from a list of lists and inspect its fundamental attributes.
**Time:** 5 minutes
**Medical Context:** Dr. Chen has handed you a new batch of lab results containing Hemoglobin (Hgb) in g/dL and Platelet Count (Plt) in 10⁹/L for three patients. Your task is to structure this data in a NumPy array for efficient analysis.

1.  Create a 2D NumPy array named `lab_results` from the following data: `[[14.5, 250], [12.8, 310], [15.2, 190]]`. Add a comment to identify the columns as `[Hgb, Plt]`.
2.  Print the `lab_results` array.
3.  Predict the `dtype` of `lab_results`. Then, print its `shape`, `ndim`, and `dtype` to verify.

**📝 Your Solution:**

In [ ]:
# TODO: Write your solution here
# Hint: Check the task description above




<details>
<summary style="background-color: #f0f0f0; padding: 10px; cursor: pointer; border-radius: 5px;">
<strong>🔍 Click to reveal solution</strong>
</summary>

<div style="padding: 10px; border-left: 3px solid #2196F3; margin-top: 10px;">

**Solution**


```python
import numpy as np

# 1. Create a 2D NumPy array named `lab_results`.
lab_data = [[14.5, 250], [12.8, 310], [15.2, 190]] # [Hgb, Plt]
lab_results = np.array(lab_data)

# 2. Print the `lab_results` array.
print("Lab Results:")
print(lab_results)

# 3. Predict the dtype, then print shape, ndim, and dtype to verify.
# Prediction: The dtype will be float64 due to the float values in the first column.
print("\nShape:", lab_results.shape)
print("Dimensions:", lab_results.ndim)
print("Data Type:", lab_results.dtype)

# Expected Output:
# Lab Results:
# [[ 14.5 250. ]
#  [ 12.8 310. ]
#  [ 15.2 190. ]]
#
# Shape: (3, 2)
# Dimensions: 2
# Data Type: float64
```
**Explanation:** Notice the `dtype` is `float64`. NumPy automatically up-cast the data type because the original list contained floating-point numbers like `14.5`. The shape `(3, 2)` confirms we have data for 3 patients (rows) with 2 measurements each (columns).
**Key Learning:** NumPy's automatic type up-casting ensures no loss of precision when mixing numeric types.


</div>
</details>

### Exercise 2: Optimize Memory for Categorical Data Intermediate

**Objective:** Create a 1D array and explicitly set its data type to optimize memory usage.
**Time:** 5 minutes
**Medical Context:** A device tracks patient falls, which can only be whole numbers. Since the number of falls will be small, using a memory-efficient integer type is good practice for large-scale studies.

1.  A device tracks patient falls. Create a 1D array named `fall_counts` from the list `[0, 1, 0, 2]`.
2.  Explicitly set its data type to `np.int8` to save memory.
3.  Print the array and its `dtype` to confirm the change.

**📝 Your Solution:**

In [ ]:
# TODO: Write your solution here
# Hint: Check the task description above




<details>
<summary style="background-color: #f0f0f0; padding: 10px; cursor: pointer; border-radius: 5px;">
<strong>🔍 Click to reveal solution</strong>
</summary>

<div style="padding: 10px; border-left: 3px solid #2196F3; margin-top: 10px;">

**Solution**


```python
import numpy as np

# 1. Create `fall_counts` with an explicit int8 dtype.
fall_counts = np.array([0, 1, 0, 2], dtype=np.int8)

# 2. Print the array and its dtype.
print("Fall Counts:", fall_counts)
print("Fall Counts Data Type:", fall_counts.dtype)

# Expected Output:
# Fall Counts: [0 1 0 2]
# Fall Counts Data Type: int8
```
**Explanation:** By passing `dtype=np.int8` during creation, we instructed NumPy to use a smaller, more memory-efficient integer type. This is a best practice when you know the range of your data and need to optimize performance, especially with millions of data points.
**Key Learning:** Explicitly setting `dtype` gives you control over memory allocation and data precision.


</div>
</details>

### Exercise 3: Generate a Treatment Schedule Intermediate

**Objective:** Use a NumPy function to generate a sequence of numbers representing a treatment schedule.
**Time:** 5 minutes
**Medical Context:** You are designing a clinical trial where a drug is administered every 6 hours over a 3-day period. You need to generate the time points for each administration.

1.  Create a 1D NumPy array named `admin_hours` that represents the hours at which the drug is administered.
2.  The schedule starts at hour 0 and continues every 6 hours for 72 hours total. The final administration should be *before* hour 72.
3.  Use `np.arange()` to generate this sequence and print the resulting array.

**📝 Your Solution:**

In [ ]:
# TODO: Write your solution here
# Hint: Check the task description above




<details>
<summary style="background-color: #f0f0f0; padding: 10px; cursor: pointer; border-radius: 5px;">
<strong>🔍 Click to reveal solution</strong>
</summary>

<div style="padding: 10px; border-left: 3px solid #2196F3; margin-top: 10px;">

**Solution**


```python
import numpy as np

# Use np.arange() to generate the schedule. The 'stop' value (72) is exclusive.
admin_hours = np.arange(0, 72, 6)

# Print the resulting array
print("Drug Administration Schedule (in hours):")
print(admin_hours)

# Expected Output:
# Drug Administration Schedule (in hours):
# [ 0  6 12 18 24 30 36 42 48 54 60 66]
```
**Explanation:** `np.arange(0, 72, 6)` starts at 0 and creates successive numbers by adding the step (6) until it reaches or exceeds the stop value (72). This is a highly efficient way to create regular time-series indices.
**Key Learning:** `np.arange()` is a powerful tool for creating numerical sequences with a constant step size, perfect for time-series data or simulations.


</div>
</details>

---

## 5. Practical Applications

- **Genomic Sequence Analysis**: A human genome contains billions of base pairs. Storing this as a NumPy array of integers (e.g., A=0, C=1, G=2, T=3) using `np.array()` is vastly more memory-efficient and faster to process than Python lists. This allows researchers to perform large-scale pattern matching and mutation detection.

- **Medical Image Processing**: An MRI or CT scan is fundamentally a 2D or 3D array of pixel intensities. NumPy is used to create and manipulate these images. For example, a data scientist might use `np.zeros()` to create an array of the same shape as an MRI scan to serve as a "mask" for isolating a tumor.

- **Real-Time Patient Monitoring**: Wearable sensors like ECGs or continuous glucose monitors generate streams of data. This time-series data is naturally stored in 1D NumPy arrays. `np.array()` can be used to capture incoming data chunks, and functions like `np.linspace()` can help in resampling data to a standard time interval for consistent analysis.

---

## 6. Summary and Key Takeaways

In this section, we've explored the fundamental methods for creating and understanding NumPy arrays, the primary data structure for numerical analysis in Python. You have moved from using basic Python lists to creating powerful, memory-efficient `ndarrays` suitable for large-scale scientific datasets.

- You can create arrays directly from lists (`np.array()`) for both 1D and 2D data.
- You can generate structured arrays using functions like `np.arange()` for sequences and `np.linspace()` for fixed-interval data.
- Placeholder arrays can be created with `np.zeros()` and `np.ones()`, which is an efficient practice for pre-allocating memory.
- Inspecting array attributes (`.shape`, `.ndim`, `.size`, `.dtype`) is crucial for understanding your data's structure.
- Managing data types with the `dtype` parameter is key to optimizing for memory and precision.

Now that you can create and inspect arrays, you are ready to learn how to access and modify their contents. The next section will cover **NumPy Indexing and Slicing**, allowing you to select, update, and manipulate specific elements and subsections of your data.

---